"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.date = void 0;
const dayjs = require("dayjs");
const AdvancedFormat = require("dayjs/plugin/advancedFormat");
const duration = require("dayjs/plugin/duration");
const utc = require("dayjs/plugin/utc");
const timezone = require("dayjs/plugin/timezone");
const relativeTime = require("dayjs/plugin/relativeTime");
const zone_1 = require("./plugins/zone");
const timeUtils_1 = require("./plugins/timeUtils");
dayjs.extend(relativeTime);
dayjs.extend(utc);
dayjs.extend(duration);
dayjs.extend(timezone);
dayjs.extend(AdvancedFormat);
dayjs.extend(zone_1.zone);
dayjs.extend(timeUtils_1.getCurrentByUnit);
dayjs.extend(timeUtils_1.getCurrentHour);
dayjs.extend(timeUtils_1.getCurrentMonth);
dayjs.extend(timeUtils_1.getCurrentWeek);
dayjs.extend(timeUtils_1.getLastMonth);
dayjs.extend(timeUtils_1.getLastWeek);
dayjs.extend(timeUtils_1.getPastDays);
exports.date = dayjs;
//# sourceMappingURL=date.js.map